CREATE DATABASE IF NOT EXISTS ProjectUrl;

USE ProjectUrl;

CREATE TABLE IF NOT EXISTS Link (
	id int UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(50) NOT NULL,
    username VARCHAR(15) UNIQUE NOT NULL,
    );
    
CREATE TABLE IF NOT EXISTS User (
	Id int UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    Title VARCHAR(50) NOT NULL,
    Description VARCHAR(200) NOT NULL,
    Url VARCHAR(100) NOT NULL,
	);
    
CREATE TABLE IF NOT EXISTS Vote (
	Id int UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	Value BOOLEAN DEFAULT true,
    IdLink int UNSIGNED NOT NULL,
    FOREIGN KEY (IdLink) REFERENCES url (Id),
    IdUser int UNSIGNED NOT NULL,
    FOREIGN KEY (IdUser) REFERENCES user (Id),
	);
